version: '3'
services:
  # Postgres
  postgres:
    image: postgres:latest
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    tty: true
